# Generated by Django 2.2.13 on 2020-10-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_auto_20201023_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='maturity',
            field=models.DateField(),
        ),
    ]
